//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.34014
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WritersToolbox.Resources {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WritersToolbox.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Byte[].
        /// </summary>
        public static byte[] add {
            get {
                object obj = ResourceManager.GetObject("add", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Details ähnelt.
        /// </summary>
        public static string AddNoteDetailsText {
            get {
                return ResourceManager.GetString("AddNoteDetailsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die DETAILS ähnelt.
        /// </summary>
        public static string AddNoteDetailsTextUpper {
            get {
                return ResourceManager.GetString("AddNoteDetailsTextUpper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die NOTIZ BEARBEITEN ähnelt.
        /// </summary>
        public static string AddNoteEditText {
            get {
                return ResourceManager.GetString("AddNoteEditText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bilder ähnelt.
        /// </summary>
        public static string AddNoteHeadlineImages{ 
            get {
                return ResourceManager.GetString("AddNoteHeadlineImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Notiz ähnelt.
        /// </summary>
        public static string AddNoteHeadlineNote {
            get {
                return ResourceManager.GetString("AddNoteHeadlineNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Aufnahme ähnelt.
        /// </summary>
        public static string AddNoteHeadlineRecord {
            get {
                return ResourceManager.GetString("AddNoteHeadlineRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Schlagwörter ähnelt.
        /// </summary>
        public static string AddNoteHeadlineTags {
            get {
                return ResourceManager.GetString("AddNoteHeadlineTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Neue Notiz ähnelt.
        /// </summary>
        public static string AddNotePageTitle {
            get {
                return ResourceManager.GetString("AddNotePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Wollen Sie die Aufnahme löschen? ähnelt.
        /// </summary>
        public static string AddNoteRecordDeleteQuestion {
            get {
                return ResourceManager.GetString("AddNoteRecordDeleteQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bitte trennen Sie die Schlagwörter mit Zeilenumbruch ähnelt.
        /// </summary>
        public static string AddNoteTagsText {
            get {
                return ResourceManager.GetString("AddNoteTagsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Titel ähnelt.
        /// </summary>
        public static string AddNoteTitleText {
            get {
                return ResourceManager.GetString("AddNoteTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die TITEL ähnelt.
        /// </summary>
        public static string AddNoteTitleTextUpper {
            get {
                return ResourceManager.GetString("AddNoteTitleTextUpper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die hinzufügen ähnelt.
        /// </summary>
        public static string AppBarAdd {
            get {
                return ResourceManager.GetString("AppBarAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die zuordnen ähnelt.
        /// </summary>
        public static string AppBarAssign {
            get {
                return ResourceManager.GetString("AppBarAssign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die zurück ähnelt.
        /// </summary>
        public static string AppBarBack {
            get {
                return ResourceManager.GetString("AppBarBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die fett ähnelt.
        /// </summary>
        public static string AppBarBold {
            get {
                return ResourceManager.GetString("AppBarBold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die abbrechen ähnelt.
        /// </summary>
        public static string AppBarCancel {
            get {
                return ResourceManager.GetString("AppBarCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die schließen ähnelt.
        /// </summary>
        public static string AppBarClose {
            get {
                return ResourceManager.GetString("AppBarClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die löschen ähnelt.
        /// </summary>
        public static string AppBarDelete {
            get {
                return ResourceManager.GetString("AppBarDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die bearbeiten ähnelt.
        /// </summary>
        public static string AppBarEdit {
            get {
                return ResourceManager.GetString("AppBarEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die kursiv ähnelt.
        /// </summary>
        public static string AppBarItalic {
            get {
                return ResourceManager.GetString("AppBarItalic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Überschreiben ähnelt.
        /// </summary>
        public static string AppBarOverwriting {
            get {
                return ResourceManager.GetString("AppBarOverwriting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die wiederherstellen ähnelt.
        /// </summary>
        public static string AppBarRestore {
            get {
                return ResourceManager.GetString("AppBarRestore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die speichern ähnelt.
        /// </summary>
        public static string AppBarSave {
            get {
                return ResourceManager.GetString("AppBarSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Erfolgreich ähnelt.
        /// </summary>
        public static string AppBarSuccessful {
            get {
                return ResourceManager.GetString("AppBarSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Zuordnung löschen ähnelt.
        /// </summary>
        public static string AppBarUnattached {
            get {
                return ResourceManager.GetString("AppBarUnattached", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die unterstrichen ähnelt.
        /// </summary>
        public static string AppBarUnderline {
            get {
                return ResourceManager.GetString("AppBarUnderline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Byte[].
        /// </summary>
        public static byte[] aufnahme {
            get {
                object obj = ResourceManager.GetObject("aufnahme", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Byte[].
        /// </summary>
        public static byte[] aufnahme_aktiv {
            get {
                object obj = ResourceManager.GetObject("aufnahme_aktiv", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Werk ändern ähnelt.
        /// </summary>
        public static string BookChangeHeadline {
            get {
                return ResourceManager.GetString("BookChangeHeadline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Wollen Sie das Werk &quot; ähnelt.
        /// </summary>
        public static string BookDeleteQuestion1 {
            get {
                return ResourceManager.GetString("BookDeleteQuestion1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &quot; löschen? ähnelt.
        /// </summary>
        public static string BookDeleteQuestion2 {
            get {
                return ResourceManager.GetString("BookDeleteQuestion2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Name des Werkes ähnelt.
        /// </summary>
        public static string BookName {
            get {
                return ResourceManager.GetString("BookName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Vorangelegte Kapitel:  ähnelt.
        /// </summary>
        public static string BooksBookTypeInfoText {
            get {
                return ResourceManager.GetString("BooksBookTypeInfoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Notiz zuweisen ähnelt.
        /// </summary>
        public static string BooksHeadlineAssignNote {
            get {
                return ResourceManager.GetString("BooksHeadlineAssignNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Überblick ähnelt.
        /// </summary>
        public static string BooksHeadlineOverview {
            get {
                return ResourceManager.GetString("BooksHeadlineOverview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die WERKE ähnelt.
        /// </summary>
        public static string BooksPageTitle {
            get {
                return ResourceManager.GetString("BooksPageTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die hinzufügen ähnelt.
        /// </summary>
        public static string TomeDetailsAddOne
        {
            get
            {
                return ResourceManager.GetString("TomeDetailsAddOne", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Kapitel ähnelt.
        /// </summary>
        public static string TomeDetailsChapter
        {
            get
            {
                return ResourceManager.GetString("TomeDetailsChapter", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ereignis ähnelt.
        /// </summary>
        public static string TomeDetailsEvent
        {
            get
            {
                return ResourceManager.GetString("TomeDetailsEvent", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ereignisse ähnelt.
        /// </summary>
        public static string TomeDetailsEventMulti
        {
            get
            {
                return ResourceManager.GetString("TomeDetailsEventMulti", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Neues ähnelt.
        /// </summary>
        public static string TomeDetailsNewOne
        {
            get
            {
                return ResourceManager.GetString("TomeDetailsNewOne", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Seite ähnelt.
        /// </summary>
        public static string TomeDetailsPage
        {
            get
            {
                return ResourceManager.GetString("TomeDetailsPage", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Seiten ähnelt.
        /// </summary>
        public static string TomeDetailsPageMulti
        {
            get
            {
                return ResourceManager.GetString("TomeDetailsPageMulti", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Typ Objekt ähnelt.
        /// </summary>
        public static string TomeDetailsTypeObject
        {
            get
            {
                return ResourceManager.GetString("TomeDetailsTypeObject", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Typ Objekte ähnelt.
        /// </summary>
        public static string TomeDetailsTypeObjectMulti
        {
            get
            {
                return ResourceManager.GetString("TomeDetailsTypeObjectMulti", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Wort ähnelt.
        /// </summary>
        public static string TomeDetailsWord
        {
            get
            {
                return ResourceManager.GetString("TomeDetailsWord", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Wörter ähnelt.
        /// </summary>
        public static string TomeDetailsWordMulti
        {
            get
            {
                return ResourceManager.GetString("TomeDetailsWordMulti", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Neuer Band ähnelt.
        /// </summary>
        public static string TomeTitleNewTome
        {
            get
            {
                return ResourceManager.GetString("TomeTitleNewTome", resourceCulture);
            }
        }


        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Kapitel 1 ähnelt.
        /// </summary>
        public static string BooksPrestructuredTomeChapter1 {
            get {
                return ResourceManager.GetString("BooksPrestructuredTomeChapter1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Nachwort ähnelt.
        /// </summary>
        public static string BooksPrestructuredTomeEpilogue {
            get {
                return ResourceManager.GetString("BooksPrestructuredTomeEpilogue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Einleitung ähnelt.
        /// </summary>
        public static string BooksPrestructuredTomeIntroduction {
            get {
                return ResourceManager.GetString("BooksPrestructuredTomeIntroduction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Gedicht 1 ähnelt.
        /// </summary>
        public static string BooksPrestructuredTomePoem1 {
            get {
                return ResourceManager.GetString("BooksPrestructuredTomePoem1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Gedicht 2 ähnelt.
        /// </summary>
        public static string BooksPrestructuredTomePoem2 {
            get {
                return ResourceManager.GetString("BooksPrestructuredTomePoem2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Geschichte 1 ähnelt.
        /// </summary>
        public static string BooksPrestructuredTomeShortstory1 {
            get {
                return ResourceManager.GetString("BooksPrestructuredTomeShortstory1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Band 1 ähnelt.
        /// </summary>
        public static string BooksPrestructuredTomeVolume1 {
            get {
                return ResourceManager.GetString("BooksPrestructuredTomeVolume1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Buchtyp ähnelt.
        /// </summary>
        public static string BookType {
            get {
                return ResourceManager.GetString("BookType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Buchtyp wählen ähnelt.
        /// </summary>
        public static string BooktypeHeadline {
            get {
                return ResourceManager.GetString("BooktypeHeadline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bitte wählen Sie einen Buchtyp ähnelt.
        /// </summary>
        public static string BooktypeText {
            get {
                return ResourceManager.GetString("BooktypeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Byte[].
        /// </summary>
        public static byte[] cancel {
            get {
                object obj = ResourceManager.GetObject("cancel", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Byte[].
        /// </summary>
        public static byte[] cancel_black {
            get {
                object obj = ResourceManager.GetObject("cancel_black", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Alle angehängten Notizen erhalten ähnelt.
        /// </summary>
        public static string CheckboxKeepNotes {
            get {
                return ResourceManager.GetString("CheckboxKeepNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Alle Bände erhalten ähnelt.
        /// </summary>
        public static string CheckboxKeepTomes {
            get {
                return ResourceManager.GetString("CheckboxKeepTomes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Angehangene Notizen beibehalten (aussortieren) ähnelt.
        /// </summary>
        public static string CheckboxKeepTypeObjectNotes {
            get {
                return ResourceManager.GetString("CheckboxKeepTypeObjectNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Alle Typobjekte erhalten ähnelt.
        /// </summary>
        public static string CheckboxKeepTypeObjects {
            get {
                return ResourceManager.GetString("CheckboxKeepTypeObjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Notizen als unsortiert markieren ähnelt.
        /// </summary>
        public static string CheckboxMarkNotesUnsigned {
            get {
                return ResourceManager.GetString("CheckboxMarkNotesUnsigned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Erstellt am:  ähnelt.
        /// </summary>
        public static string ConverterBookCreationDate {
            get {
                return ResourceManager.GetString("ConverterBookCreationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Dauer  ähnelt.
        /// </summary>
        public static string ConverterDuration {
            get {
                return ResourceManager.GetString("ConverterDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Kapitelanzahl:  ähnelt.
        /// </summary>
        public static string ConverterNumberOfChapter {
            get {
                return ResourceManager.GetString("ConverterNumberOfChapter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Anzahl Notizen:  ähnelt.
        /// </summary>
        public static string ConverterNumberOfNotes {
            get {
                return ResourceManager.GetString("ConverterNumberOfNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  NOTIZEN ähnelt.
        /// </summary>
        public static string ConverterSubtitleNotes {
            get {
                return ResourceManager.GetString("ConverterSubtitleNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die wird nicht verwendet ähnelt.
        /// </summary>
        public static string ConverterUnused {
            get {
                return ResourceManager.GetString("ConverterUnused", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die wird verwendet ähnelt.
        /// </summary>
        public static string ConverterUsed {
            get {
                return ResourceManager.GetString("ConverterUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Byte[].
        /// </summary>
        public static byte[] delete {
            get {
                object obj = ResourceManager.GetObject("delete", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sie müssen mindestens Details der Notiz eingeben!! ähnelt.
        /// </summary>
        public static string ErrorDetails {
            get {
                return ResourceManager.GetString("ErrorDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sie müssen einen Namen eingeben ähnelt.
        /// </summary>
        public static string ErrorName {
            get {
                return ResourceManager.GetString("ErrorName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Speichern fehlgeschlagen ähnelt.
        /// </summary>
        public static string ErrorSave {
            get {
                return ResourceManager.GetString("ErrorSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Wir haben nicht verstanden, versuchen Sie nochmal !! ähnelt.
        /// </summary>
        public static string ErrorSpeechToText {
            get {
                return ResourceManager.GetString("ErrorSpeechToText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Warnung ähnelt.
        /// </summary>
        public static string ErrorWarning {
            get {
                return ResourceManager.GetString("ErrorWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Typobjekt anhängen ähnelt.
        /// </summary>
        public static string EventAssignTypObject {
            get {
                return ResourceManager.GetString("EventAssignTypObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Finaltext ähnelt.
        /// </summary>
        public static string EventDetailHeadline1 {
            get {
                return ResourceManager.GetString("EventDetailHeadline1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Notizen ähnelt.
        /// </summary>
        public static string EventDetailHeadline2 {
            get {
                return ResourceManager.GetString("EventDetailHeadline2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Typobjekte ähnelt.
        /// </summary>
        public static string EventDetailHeadline3 {
            get {
                return ResourceManager.GetString("EventDetailHeadline3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die EVENT ähnelt.
        /// </summary>
        public static string EventDetailTitle {
            get {
                return ResourceManager.GetString("EventDetailTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Byte[].
        /// </summary>
        public static byte[] info_checked {
            get {
                object obj = ResourceManager.GetObject("info_checked", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Byte[].
        /// </summary>
        public static byte[] info_unchecked {
            get {
                object obj = ResourceManager.GetObject("info_unchecked", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die vorwärts ähnelt.
        /// </summary>
        public static string MediaPlayerForward {
            get {
                return ResourceManager.GetString("MediaPlayerForward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die pp ähnelt.
        /// </summary>
        public static string MediaPlayerPause {
            get {
                return ResourceManager.GetString("MediaPlayerPause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die rückwärts ähnelt.
        /// </summary>
        public static string MediaPlayerReward {
            get {
                return ResourceManager.GetString("MediaPlayerReward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die stopp ähnelt.
        /// </summary>
        public static string MediaPlayerStop {
            get {
                return ResourceManager.GetString("MediaPlayerStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Eine Notiz mit diesem Name ist bereits in dem Typeobjekt µ1 Vorhanden. ähnelt.
        /// </summary>
        public static string MeldungUeberschreibungNoteInTypeObject1 {
            get {
                return ResourceManager.GetString("MeldungUeberschreibungNoteInTypeObject1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Möchtest du dieNotiz überschreiben ? ähnelt.
        /// </summary>
        public static string MeldungUeberschreibungNoteInTypeObject2 {
            get {
                return ResourceManager.GetString("MeldungUeberschreibungNoteInTypeObject2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Eine Notiz mit diesem Name ist bereits im dem Ereignis ähnelt.
        /// </summary>
        public static string MeldungVorhandeneNotizinEvent1 {
            get {
                return ResourceManager.GetString("MeldungVorhandeneNotizinEvent1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Vorhanden.  ähnelt.
        /// </summary>
        public static string MeldungVorhandeneNotizinEvent2 {
            get {
                return ResourceManager.GetString("MeldungVorhandeneNotizinEvent2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Möchtest du die Notiz überschreiben ? ähnelt.
        /// </summary>
        public static string MeldungVorhandeneNotizinEvent3 {
            get {
                return ResourceManager.GetString("MeldungVorhandeneNotizinEvent3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Die Zuordnung der Notiz µ1 wurde erfolgreich zu dem µ2 hinzugefügt ähnelt.
        /// </summary>
        public static string MeldungZuordnungErfolgreich {
            get {
                return ResourceManager.GetString("MeldungZuordnungErfolgreich", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Es ist nur möglich ein Werk zu löschen, wenn keine Bände mehr existieren. ähnelt.
        /// </summary>
        public static string MessageDeleteBook {
            get {
                return ResourceManager.GetString("MessageDeleteBook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Fehler ähnelt.
        /// </summary>
        public static string MessageError {
            get {
                return ResourceManager.GetString("MessageError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Byte[].
        /// </summary>
        public static byte[] micro {
            get {
                object obj = ResourceManager.GetObject("micro", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Neues Werk ähnelt.
        /// </summary>
        public static string NewBook {
            get {
                return ResourceManager.GetString("NewBook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ändern ähnelt.
        /// </summary>
        public static string NewBookEditBooktype {
            get {
                return ResourceManager.GetString("NewBookEditBooktype", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Neuer Band erstellen ähnelt.
        /// </summary>
        public static string NewTomeTemplate {
            get {
                return ResourceManager.GetString("NewTomeTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Titel ähnelt.
        /// </summary>
        public static string NewTomeTitleText {
            get {
                return ResourceManager.GetString("NewTomeTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Neuer Typ ähnelt.
        /// </summary>
        public static string NewType {
            get {
                return ResourceManager.GetString("NewType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Farbe ähnelt.
        /// </summary>
        public static string NewTypeColorText {
            get {
                return ResourceManager.GetString("NewTypeColorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Neues Objekt ähnelt.
        /// </summary>
        public static string NewTypeObject {
            get {
                return ResourceManager.GetString("NewTypeObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Titel ähnelt.
        /// </summary>
        public static string NewTypeTitleText {
            get {
                return ResourceManager.GetString("NewTypeTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Byte[].
        /// </summary>
        public static byte[] note {
            get {
                object obj = ResourceManager.GetObject("note", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Wollen Sie alle  ähnelt.
        /// </summary>
        public static string NoteDeleteQuestion1 {
            get {
                return ResourceManager.GetString("NoteDeleteQuestion1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  Notizen löschen? ähnelt.
        /// </summary>
        public static string NoteDeleteQuestion2 {
            get {
                return ResourceManager.GetString("NoteDeleteQuestion2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Wollen Sie die Notiz löschen? ähnelt.
        /// </summary>
        public static string NoteDeleteQuestionSingle {
            get {
                return ResourceManager.GetString("NoteDeleteQuestionSingle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Byte[].
        /// </summary>
        public static byte[] notiz {
            get {
                object obj = ResourceManager.GetObject("notiz", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Byte[].
        /// </summary>
        public static byte[] off {
            get {
                object obj = ResourceManager.GetObject("off", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Byte[].
        /// </summary>
        public static byte[] on {
            get {
                object obj = ResourceManager.GetObject("on", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Byte[].
        /// </summary>
        public static byte[] pause_reordButton {
            get {
                object obj = ResourceManager.GetObject("pause_reordButton", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Aufnahme ähnelt.
        /// </summary>
        public static string PivotHeaderAufnahme {
            get {
                return ResourceManager.GetString("PivotHeaderAufnahme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bilder ähnelt.
        /// </summary>
        public static string PivotHeaderBilder {
            get {
                return ResourceManager.GetString("PivotHeaderBilder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Byte[].
        /// </summary>
        public static byte[] play {
            get {
                object obj = ResourceManager.GetObject("play", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Byte[].
        /// </summary>
        public static byte[] play_reordButton {
            get {
                object obj = ResourceManager.GetObject("play_reordButton", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die LeftToRight ähnelt.
        /// </summary>
        public static string ResourceFlowDirection {
            get {
                return ResourceManager.GetString("ResourceFlowDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die de-de ähnelt.
        /// </summary>
        public static string ResourceLanguage {
            get {
                return ResourceManager.GetString("ResourceLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Alle auswählen ähnelt.
        /// </summary>
        public static string SelectAll {
            get {
                return ResourceManager.GetString("SelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Backups verwalten ähnelt.
        /// </summary>
        public static string SettingsBackupButton {
            get {
                return ResourceManager.GetString("SettingsBackupButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sicherung: ähnelt.
        /// </summary>
        public static string SettingsBackupText {
            get {
                return ResourceManager.GetString("SettingsBackupText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Buch exportieren ähnelt.
        /// </summary>
        public static string SettingsExportButton {
            get {
                return ResourceManager.GetString("SettingsExportButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Export: ähnelt.
        /// </summary>
        public static string SettingsExportText {
            get {
                return ResourceManager.GetString("SettingsExportText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Deutsch ähnelt.
        /// </summary>
        public static string SettingsLangDE {
            get {
                return ResourceManager.GetString("SettingsLangDE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Englisch ähnelt.
        /// </summary>
        public static string SettingsLangENG {
            get {
                return ResourceManager.GetString("SettingsLangENG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sprache ähnelt.
        /// </summary>
        public static string SettingsLangText {
            get {
                return ResourceManager.GetString("SettingsLangText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Einstellungen ähnelt.
        /// </summary>
        public static string SettingsTitle {
            get {
                return ResourceManager.GetString("SettingsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Byte[].
        /// </summary>
        public static byte[] speaker_reordButton {
            get {
                object obj = ResourceManager.GetObject("speaker_reordButton", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Byte[].
        /// </summary>
        public static byte[] speichern {
            get {
                object obj = ResourceManager.GetObject("speichern", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Byte[].
        /// </summary>
        public static byte[] speichernUnter {
            get {
                object obj = ResourceManager.GetObject("speichernUnter", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Werke ähnelt.
        /// </summary>
        public static string StartpageBooks {
            get {
                return ResourceManager.GetString("StartpageBooks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Neue Notiz ähnelt.
        /// </summary>
        public static string StartpageNewNote {
            get {
                return ResourceManager.GetString("StartpageNewNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Einstellungen ähnelt.
        /// </summary>
        public static string StartpageSettings {
            get {
                return ResourceManager.GetString("StartpageSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Papierkorb ähnelt.
        /// </summary>
        public static string StartpageTrashbin {
            get {
                return ResourceManager.GetString("StartpageTrashbin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Typen ähnelt.
        /// </summary>
        public static string StartpageTypes {
            get {
                return ResourceManager.GetString("StartpageTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Unsortierte Notizen ähnelt.
        /// </summary>
        public static string StartpageUnsortedNotes {
            get {
                return ResourceManager.GetString("StartpageUnsortedNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Byte[].
        /// </summary>
        public static byte[] struktur_checked {
            get {
                object obj = ResourceManager.GetObject("struktur_checked", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Byte[].
        /// </summary>
        public static byte[] struktur_unchecked {
            get {
                object obj = ResourceManager.GetObject("struktur_unchecked", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Abbrechen ähnelt.
        /// </summary>
        public static string TextCancel {
            get {
                return ResourceManager.GetString("TextCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Löschen ähnelt.
        /// </summary>
        public static string TextDelete {
            get {
                return ResourceManager.GetString("TextDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Speichern ähnelt.
        /// </summary>
        public static string TextSave {
            get {
                return ResourceManager.GetString("TextSave", resourceCulture);
            }
        }
        
      
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Es werden alle markierten und dazugehörigen, hierarchisch untergeordnete Daten permanent gelöscht.  ähnelt.
        /// </summary>
        public static string TrashbinDeleteQuestion {
            get {
                return ResourceManager.GetString("TrashbinDeleteQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Papierkorb ähnelt.
        /// </summary>
        public static string TrashbinHeadline {
            get {
                return ResourceManager.GetString("TrashbinHeadline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Wollen Sie den Typ &quot; ähnelt.
        /// </summary>
        public static string TypeDeleteQuestion1 {
            get {
                return ResourceManager.GetString("TypeDeleteQuestion1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &quot; löschen? ähnelt.
        /// </summary>
        public static string TypeDeleteQuestion2 {
            get {
                return ResourceManager.GetString("TypeDeleteQuestion2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Byte[].
        /// </summary>
        public static byte[] typen_checked {
            get {
                object obj = ResourceManager.GetObject("typen_checked", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Byte[].
        /// </summary>
        public static byte[] typen_unchecked {
            get {
                object obj = ResourceManager.GetObject("typen_unchecked", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Willst du deine Änderungen wirklich verwerfen? ähnelt.
        /// </summary>
        public static string TypeObjectAddCancelText {
            get {
                return ResourceManager.GetString("TypeObjectAddCancelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Titel eingeben ähnelt.
        /// </summary>
        public static string TypeObjectAddTitleText {
            get {
                return ResourceManager.GetString("TypeObjectAddTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Notiz zuweisen ähnelt.
        /// </summary>
        public static string TypeObjectAssign {
            get {
                return ResourceManager.GetString("TypeObjectAssign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Wollen Sie das Typobjekt &quot; ähnelt.
        /// </summary>
        public static string TypeObjectDeleteQuestion1 {
            get {
                return ResourceManager.GetString("TypeObjectDeleteQuestion1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &quot; löschen? ähnelt.
        /// </summary>
        public static string TypeObjectDeleteQuestion2 {
            get {
                return ResourceManager.GetString("TypeObjectDeleteQuestion2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Möchtest du die Typobjekte wirklich löschen? ähnelt.
        /// </summary>
        public static string TypeObjectsDeleteQuestion {
            get {
                return ResourceManager.GetString("TypeObjectsDeleteQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Charakter ähnelt.
        /// </summary>
        public static string TypesHeadlineCharacter {
            get {
                return ResourceManager.GetString("TypesHeadlineCharacter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Kreaturen ähnelt.
        /// </summary>
        public static string TypesHeadlineCreatures {
            get {
                return ResourceManager.GetString("TypesHeadlineCreatures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Schauplatz ähnelt.
        /// </summary>
        public static string TypesHeadlineSetting {
            get {
                return ResourceManager.GetString("TypesHeadlineSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die TYPEN ähnelt.
        /// </summary>
        public static string TypesPageTitle {
            get {
                return ResourceManager.GetString("TypesPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Unsortierte Notizen ähnelt.
        /// </summary>
        public static string UnsortedNotesHeadline {
            get {
                return ResourceManager.GetString("UnsortedNotesHeadline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Byte[].
        /// </summary>
        public static byte[] zurueck {
            get {
                object obj = ResourceManager.GetObject("zurueck", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
